{
 "title": "Balance",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "balance_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "KRW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance{currency=\"KRW\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  },
  {
   "title": "XRP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance{currency=\"XRP\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  },
  {
   "title": "ADA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "balance{currency=\"ADA\"}",
     "legendFormat": "{{currency}}"
    }
   ]
  }
 ]
}